on: 
  push:
    tags:
      - v*
name: Production Build & Deploy
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run build & deploy script
      id: build-and-deploy
      uses: ./build/action
      with:
        target: 'production'
      env: 
        ENV_KEY: ${{ secrets.ENV_KEY }}
        ENV_LOGIN: 'LOGIN'